### ISSUE TITLE
App Crashes after Patient books an Appointment

### ISSUE THREAD

**Issue by GabrielTidy** [freezy04/Runtime-Terror#16]
E/WindowManager: android.view.WindowLeaked: Activity com.example.mobidoc.ui.Appointment.Booking has leaked window DecorView@3465626[Booking] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:711)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:701)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:108)
        at android.app.Dialog.show(Dialog.java:340)
        at com.example.mobidoc.ui.Appointment.Booking.BookAppointment(Booking.java:151)
        at com.example.mobidoc.ui.Appointment.Booking.access$000(Booking.java:35)
        at com.example.mobidoc.ui.Appointment.Booking$4$1.onClick(Booking.java:134)

**Comment by GabrielTidy** [comment]
Fixed
